---
- hosts: server
  gather_facts: false
  remote_user: root
  vars_files:
   - vars/default.yml

  tasks:

# =============== Prepare necessary packages =============== # 

   - name: Use apt_get
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: Install LAMP Packages (apache,mysql,php)
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

   - name: Install PHP Extensions
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

# =============== Apache Configuration =============== #

   - name: Create document root
     file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: '0755'

   - name: Set up Apache VirtualHost
     template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"
     notify: Reload Apache

   - name: Enable rewrite module
     shell: /usr/sbin/a2enmod rewrite
     notify: Reload Apache

   - name: Enable new site
     shell: /usr/sbin/a2ensite {{ http_conf }}
     notify: Reload Apache

   - name: Disable default Apache site
     shell: /usr/sbin/a2dissite 000-default.conf
     notify: Restart Apache

# =============== MySQL Configuration =============== #

   - name: Set root pw
     mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Remove all anonymous user accounts
     mysql_user:
      name: ''
      host_all: yes
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"

   - name: Remove the MySQL test database
     mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"

   - name: Creates database for WordPress
     mysql_db:
      name: "{{ mysql_db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

   - name: Create MySQL user for WordPress
     mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"

# =============== UFW Configuration =============== #

   - name: "UFW - Allow HTTP on port {{ http_port }}"
     ufw:
      rule: allow
      port: "{{ http_port }}"
      proto: tcp

# =============== WordPress Configuration =============== #

   - name: Download and unpack latest WordPress
     unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "/var/www/{{ http_host }}"
      remote_src: yes
      creates: "/var/www/{{ http_host }}/wordpress"

   - name: Set ownership
     file:
      path: "/var/www/{{ http_host }}"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

   - name: Set permissions for directories
     shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"

   - name: Set permissions for files
     shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"

   - name: Set up wp-config
     template:
      src: "files/wp-config.php.j2"
      dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"

# =============== Manage Service From notify script =============== #

  handlers:
   - name: Reload Apache
     service:
      name: apache2
      state: reloaded

   - name: Restart Apache
     service:
      name: apache2
      state: restarted
